# Generated by Django 3.1.7 on 2021-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210312_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
